#!/usr/bin/env sh

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
java -jar $DIR/../build/tasks/_protoc-gen-kotlin-lens_executableJarJvm/protoc-gen-kotlin-lens-jvm-executable.jar "$@"